spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 50MB
      location: C:\\Users\\SSAFY\\Desktop\\temp-file\\
  data:
    mongodb:
      uri: mongodb+srv://S11P21D207:7rPaud@ssafy.ngivl.mongodb.net/S11P21D207?authSource=admin&retryWrites=true&w=majority
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/ezdg?useSSL=false&serverTimezone=UTC
  #    username: root
  #    password: 1234
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #      dialect: org.hibernate.dialect.MySQLDialect  #
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: alpha

path:
  java-library-project-path: C:\\Users\\SSAFY\\Desktop\\generated\\
  api-server-project-path: C:\\Users\\SSAFY\\Desktop\\generated\\
  temp-file-path: C:\\Users\\SSAFY\\Desktop\\temp-file\\
  release-sh-path: C:\\Users\\SSAFY\\Desktop\\

admin:
  base-url: /admin

external:
  api:
    fastApi: http://k11d201.p.ssafy.io/croller
